### ISSUE TITLE
Make IdentityAccess and TaskManager standalone apps

### ISSUE THREAD

**Issue by gorkalaucirica** [kreta/kreta#196]
Once done remove the hack introduced in #195

**Comment by gorkalaucirica** [comment]
@benatespina Now that we have standalone apps can we remove the hack?

**Comment by benatespina** [comment]
Yeah, you're right!

**Comment by benatespina** [comment]
This commit 4d8418638c3c24ee2c716ca4a230dd3d2470f7b8 solves this issue
