### ISSUE TITLE
500 while registering on kreta.io

### ISSUE THREAD

**Issue by tigitz** [kreta/Kreta#387]
Hello,

I can't register on the demo site because of this error:

![image](https://user-images.githubusercontent.com/1524501/28780730-1f660d2e-7608-11e7-8d30-7cb27c5984d9.png)

**Comment by benatespina** [comment]
Hi, thanks for reporting the issue, the above PR solves the problem. You can check the reason in this class. ;)

https://github.com/kreta/Kreta/blob/master/IdentityAccess/src/Kreta/IdentityAccess/Domain/Model/User/Username.php
